on:
  push:
    branches:
      - main





jobs:
  build:
    runs-on: ubuntu-latest

    
    steps:
      - name: 'before checkout'
        run: ls


      - uses: actions/checkout@v3


      - name: 'after checkout'
        run: ls


      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: List files after checkout
        run: ls -al

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/learn_push_image .    
      
      - name: Push image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/learn_push_image



          
      


      
         



































